name: mentor_app_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+12

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  protobuf: ^2.1.0
  web_socket_channel: ^2.2.0
  uuid: ^3.0.6
  flutter_webrtc: ^0.9.20
  # 在測試webrtc時使用的是^0.13.3 為了google_fonts改為^0.12.0+2
  wakelock: ^0.6.2
  shared_preferences: ^2.0.15
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2
  scrollable_positioned_list: ^0.3.1
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  dio: ^4.0.6
  google_sign_in: ^5.4.2
  google_sign_in_web: ^0.10.2
  flutter_background: ^1.1.0
  intl: ^0.17.0
  firebase_core: ^2.1.1
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.0.3
  toast: ^0.3.0
  flutter_launcher_icons: ^0.10.0
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  time_range_picker: ^2.2.0
  permission_handler: ^10.2.0
  swipe_cards: ^1.0.0
  flutter_screenutil: ^5.6.0
  pay: ^1.0.11
  flutter_rating_bar: ^4.0.1
  device_info_plus: ^4.0.0
  cached_network_image: ^3.2.0
  get: ^4.6.5
  datepicker_dropdown: ^0.0.7+2
  sign_button: ^2.0.2
  flutter_native_splash: ^2.2.16
  internet_connection_checker: 1.0.0+1
  fluttertoast: ^8.2.1
  flutter_list_view: ^1.1.21
  flutter_riverpod: ^2.3.2
  flutter_svg_provider: ^1.0.3
  readmore: ^2.1.0
  path_provider: ^2.0.14
  http: ^0.13.5

# RUN COMMAND: flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/icons/logo.png"
  adaptive_icon_foreground: "assets/icons/logo.png"
  adaptive_icon_background: "#57AEAF"
  android: true
  ios: true

# RUN COMMAND: flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#4faaef"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    icon_background_color: "#4faaef"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  objectbox_generator: ^1.6.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
