enum ChatMessageState {
  SELF_SIMPLE_MESSAGE,
  SELF_READ_MESSAGE,
  OTHERS_SIMPLE_MESSAGE,
  OTHERS_READ_MESSAGE,
  OTHERS_CLASS_TOKEN_MESSAGE,
  SELF_CLASS_TOKEN_MESSAGE,
  USED_CLASS_TOKEN_MESSAGE
}